In [2]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import time
import sys

l = range(1000)
print(sys.getsizeof(1)*len(l))

a = np.arange(1000)
print(a.size*a.itemsize)

28000
4000


In [4]:
SIZE = 10000000

l1 = range(SIZE)
l2 = range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

#list
start = time.time()
result =  [(x+y) for x,y in zip(l1,l2)]
print("python list ::" , (time.time() -start)*1000)

#numpy array
start = time.time()
result1 = a1 + a2
print("numpy took :" , (time.time()-start)*1000)

python list :: 1336.1115455627441
numpy took : 17.708539962768555


In [12]:
b= np.array([[1,2,3],[4,5,6]])

b[[0][0]]

array([1, 2, 3])

In [13]:
b.ndim

2

In [14]:
b.itemsize

4

In [15]:
b.dtype

dtype('int32')

In [21]:
b.shape

(2, 3)

In [16]:
c= np.array([[1,2,3],[4,5,6]] , dtype=np.float64)

In [17]:
c.itemsize

8

In [18]:
c.dtype

dtype('float64')

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
c.shape

(2, 3)

In [25]:
d= np.array([[1,2],[3,4],[5,6]] , dtype=complex)

In [26]:
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
#list
l=range(5)

In [31]:
l

range(0, 5)

In [34]:
#numpy array

np.arange(1,5)

array([1, 2, 3, 4])

In [39]:
np.arange(1,5,2) #(start,end,step)

array([1, 3])

In [40]:
np.linspace(1,5,10) #(start,end,numbers wanted between start and end)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [41]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [42]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
b.shape

(2, 3)

In [44]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
b.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [47]:
b.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [48]:
b.ravel() #return one dimentional array , don't change the original array

array([1, 2, 3, 4, 5, 6])

In [49]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
b.min()

1

In [52]:
b.max()

6

In [53]:
b.sum()

21

In [54]:
b.sum(axis=0) #axis=0 for column

array([5, 7, 9])

In [55]:
b.sum(axis=1) #axis=1 for raw

array([ 6, 15])

In [58]:
np.sqrt(b) #square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [59]:
np.std(b) #standard deviation

1.707825127659933

In [60]:
 b

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
e=np.array([[6,7,8],[9,10,11]])
e

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [63]:
b+e


array([[ 7,  9, 11],
       [13, 15, 17]])

In [64]:
b-e

array([[-5, -5, -5],
       [-5, -5, -5]])

In [65]:
b*e

array([[ 6, 14, 24],
       [36, 50, 66]])

In [66]:
b/e

array([[0.16666667, 0.28571429, 0.375     ],
       [0.44444444, 0.5       , 0.54545455]])

In [71]:
#python list
n=[6,7,8]
n[0:2]

[6, 7]

In [72]:
n[-1]

8

In [74]:
#numpy array
#for 1D

m=np.array([6,7,8])
m[0:2]             #same as python list

array([6, 7])

In [75]:
#mulyi dimension

o=np.array([[6,7,8],[1,2,3],[9,3,2]])
o

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [78]:
o[1,2]        #2'nd raw , 3'rd column : element[3]

3

In [79]:
o[0:2,2]   # 0 and 1 'st raw , 3'rd column : elements [8,3]

array([8, 3])

In [81]:
o[-1]

array([9, 3, 2])

In [83]:
o[-1,0:2]

array([9, 3])

In [85]:
o[:,1:] #or o[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [87]:
for row in o:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [89]:
for cell in o.flat:
    print(cell)                    #by flat method : convert into 1 D

6
7
8
1
2
3
9
3
2


In [103]:
p=np.arange(6).reshape(3,2)
p

array([[0, 1],
       [2, 3],
       [4, 5]])

In [104]:
q=np.arange(6,12).reshape(3,2)
q

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [105]:
np.vstack((p,q))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [106]:
np.hstack((p,q))


array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [108]:
r=np.arange(30).reshape(2,15)
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [112]:
np.hsplit(r,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [113]:
np.vsplit(r,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [114]:
s=np.arange(12).reshape(3,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
t= s>5
t

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
t.dtype

dtype('bool')

In [117]:
s[t]

array([ 6,  7,  8,  9, 10, 11])

In [122]:
s[t]=3
s   #where value is true , it assign = 3

array([[0, 1, 2, 3],
       [4, 5, 3, 3],
       [3, 3, 3, 3]])

# Numpy tutorial: iterable numpy array using nditer

In [145]:
u= np.arange(12).reshape(3,4)
u

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Using normal for loop iteration

In [146]:
for row in u:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


 ### For loop with flatten

In [147]:
for cell in u.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


## nditer
### C style orderning

In [148]:
for x in np.nditer(u,order="C"):
    print(x)                               #iterate threw raw

0
1
2
3
4
5
6
7
8
9
10
11


### Fortan style orderning

In [149]:
for x in np.nditer(u,order="F"):
    print(x)                              #iterate threw column

0
4
8
1
5
9
2
6
10
3
7
11


### external_loop

In [150]:
for x in np.nditer(u, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


### Modify array values while iterating

In [151]:
for x in np.nditer(u, op_flags=["readwrite"]):
    x[...]=x*x
u

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [152]:
for x in np.nditer(u, op_flags=["readwrite"]):
    x[...]=x*3

In [153]:
u

array([[  0,   3,  12,  27],
       [ 48,  75, 108, 147],
       [192, 243, 300, 363]])

### Iterate two broadcastable arrays concurrently

In [154]:
v= np.arange(3,15,4).reshape(3,1)
v

array([[ 3],
       [ 7],
       [11]])

In [155]:
for x, y in np.nditer([u,v]):
    print(x,y)

0 3
3 3
12 3
27 3
48 7
75 7
108 7
147 7
192 11
243 11
300 11
363 11
